application/application/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', include("hello.urls")),
    path('newyear/', include("newyear.urls")),
    path('tasks/', include("tasks.urls")),
]

application/hello/urls.py
from django.urls import path 

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("siva", views.siva, name="siva"),
    path("karthi", views.karthi, name="karthi"),
    path("<str:name>", views.greet, name="greet")
]

application/newyear/urls.py
from django.urls import path 

from . import views

urlpatterns = [
    path("", views.index, name="index"),
]

application/tasks/urls.py
from django.urls import path 

from  . import views

app_name = "tasks"
urlpatterns = [
    path("", views.index, name="index"),
    path("add", views.add, name="add")
]

application/hello/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, "hello/hello.html")

def siva(request):
    return HttpResponse("Hello, Siva!")

def karthi(request):
    return HttpResponse("Hello, Karthi!")

def greet(request, name):
    return render(request, "hello/greet.html", {
        "name": name.capitalize()
    })

application/newyear/views.py
import datetime

from django.shortcuts import render

# Create your views here.
def index(request):
    now = datetime.datetime.now()
    return render(request, "newyear/index.html", {
        "newyear": now.month == 1 and now.day == 2
    })

application/tasks/views.py
from django import forms
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

# tasks = []

class NewTaskForm(forms.Form):
    task = forms.CharField(label="New Task")

# Create your views here.
def index(request):
    if "tasks" not in request.session:
        request.session["tasks"] = []

    return render(request, "tasks/index.html", {
        "tasks": request.session["tasks"]
    })

def add(request):
    if request.method == "POST":
        form = NewTaskForm(request.POST)

        if form.is_valid():
            task = form.cleaned_data["task"]
            request.session["tasks"] += [task]
            return HttpResponseRedirect(reverse("tasks:index"))
        else: 
            return render(request, "task/add.html", {
                "form": form
            })

    return render(request, "tasks/add.html", {
        "form": NewTaskForm()
    })

application/hello/templates/hello/greet.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Greet</title>
</head>
<body>
    <h1>Hello, {{ name }}!</h1>
</body>
</html>

application/hello/templates/hello/hello.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hello!</title>
</head>
<body>
    <h1>Hello, World!</h1>
</body>
</html>

application/newyear/templates/newyear/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'newyear/styles.css' %}">
    <title>It it New Year's?</title>
</head>
<body>
    {% if newyear %}
        <h1>YES</h1>
    {% else %}
        <h1>NO</h1>
    {% endif %}
</body>
</html>

application/tasks/templates/tasks/add.html
{% extends "tasks/layout.html" %}

{% block title %}
    Tasks
{% endblock %}

{% block body %}
    <h1>Add Task</h1>
    <form action="{% url 'tasks:add' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit">
    </form>
    <a href="{% url 'tasks:index' %}">View Tasks</a>
{% endblock %}

application/tasks/templates/tasks/index.html
{% extends "tasks/layout.html" %}

{% block title %}
    Tasks
{% endblock %}

{% block body %}
    <h2>Tasks</h2>
    <ul>
        {% for task in tasks %}
            <li><h3>{{ task }}</h3></li>
        {% empty %}
            <li><h3>No tasks.</h3></li>
        {% endfor %}
    </ul>
    <a href="{% url 'tasks:add' %}">Add a new task</a>
{% endblock %}

application/tasks/templates/tasks/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>